### ISSUE TITLE
[QUESTION] Is there anyone actively supporting this repo?

### ISSUE THREAD

**Issue by msmcconnell** [gaia-platform/GaiaPlatform#1553]
The Gaia platform is very interesting, but I am wondering what the level of community support there is at the moment. Are there any active maintainers? 

If there's not, is there any documentation of planned but missing features or existing issues?

**Comment by senderista** [comment]
I am actively developing a fork of (for now) just the key-value transactional database, but AFAIK there is currently no active development or maintenance on the main repository (the company that developed it went out of business). I would be curious what your potential use cases for the platform are? As I said, I'm actively working on a fork, and need to prioritize my work, so I would be interested in which features appear most useful to potential users.

**Comment by msmcconnell** [comment]
Thanks for the response!
We are looking at a world model build out for a robotics platform. The potential use case I see is simplifying storage and access to data where detected objects, semantic information, and localized rules can all be easily linked and accessed. It seems like gaia would remove some of the boilerplate logic to maintain data consistency between components. 

What kinds of changes are planned for your fork? Is there a set of issues you are resolving?

**Comment by senderista** [comment]
My fork is (for now) only addressing performance issues with the transactional database. I plan to eventually reintegrate schema support, but not the declarative rules functionality. I think the database is of independent interest from the rest of the platform, but this is probably not the appropriate forum for discussing a private fork of the repository.

If you'd like to continue this discussion (I certainly would!), my email is tobin.d.baker@gmail.com.

**Comment by msmcconnell** [comment]
Thanks for the info. My team will discuss a bit on this and if we want to keep the conversation going. I'll reach out through email.
